### ISSUE TITLE
Error running createServiceRegistry() example in EDS guide

### ISSUE THREAD

**Issue by bugvish** [Verizon/5GEdgeTutorials#7]
Following the instructions in https://github.com/Verizon/5GEdgeTutorials/blob/main/edge-discovery/README.md is successful until the createServiceRegistry() call in Step 2, which returns the following error: 

`TypeError: createServiceRegistry() missing 1 required positional argument: 'fqdns'.`  

Any guidance would be appreciated.  Thank you.

**Comment by rhbelson** [comment]
Resolved in latest version of SDK
